# Use postgres/example user/password credentials
#version: '3.1'

#services:

#  db:
#    image: postgres
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: "u"
#      POSTGRES_PASSWORD: "u"
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

#  database:
#    image: mysql
#    volumes:
#      - dbdata:/var/lib/mysql
#    environment:
#      - "MYSQL_DATABASE=homestead"
#      - "MYSQL_USER=homestead"
#      - "MYSQL_PASSWORD=secret"
#      - "MYSQL_ROOT_PASSWORD=secret"
#    ports:
#        - "3306:3306"
#
#  phpmyadmin:
#    depends_on:
#      - database
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    ports:
#      - 89:80
#    environment:
#      PMA_HOST: database
#      MYSQL_ROOT_PASSWORD: secret
#
#volumes:
#  dbdata:
version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: home
      MYSQL_USER: home
      MYSQL_PASSWORD: home
      MYSQL_ROOT_PASSWORD: home
#    volumes:
#      - ./docker/mysql/conf:/etc/mysql/conf.d
#      - ./docker/mysql/db:/var/lib/mysql

  php:
    image: php
#      volumes:
#          - ./:/var/lib/mysql
#      networks:
#          - default
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
          - db:db
      ports:
          - 8000:80
      environment:
          MYSQL_USER: home
          MYSQL_PASSWORD: home
          MYSQL_ROOT_PASSWORD: home
